balena-io-modules/ui-shared-components

package-lock.json, package.json
=> Add missing lint-staged lib

src/components/CookiesBanner/CoockiesBanner.stories.tsx, src/components/CookiesBanner/index.tsx, src/utils/storage.ts
=> Add CookiesBanner component

src/components/CookiesBanner/CoockiesBanner.stories.tsx, src/components/CookiesBanner/index.tsx, src/index.ts
Change-type: patcFix CookiesBanner export and add requied
=> Fix CookiesBanner export and add requied

.storybook/preview.tsx, src/components/CookiesBanner/CoockiesBanner.stories.tsx, src/components/CookiesBanner/index.tsx, src/contexts/AnalyticsContext.tsx, src/contexts/CookiesContext.tsx, src/index.ts
=> Add CookiesContext and fix AnalyticsContext

src/components/DialogWithCloseButton/DialogWithCloseButton.stories.tsx, src/components/DialogWithCloseButton/index.tsx, src/index.ts, src/theme.ts
Add DialogWithCloseButton component and Dialog styling
Connects-to: https://github.com/balena-io/balena-ui/pull/6072
=> Add DialogWithCloseButton component and Dialog styling

package-lock.json, package.json, src/components/VirtualizedAutocomplete/VirtualizedAutocomplete.stories.tsx, src/components/VirtualizedAutocomplete/index.tsx, src/index.ts, tsconfig.esm5.json, tsconfig.json
Add VirtualizedAutocomplete component
=> Add VirtualizedAutocomplete component

package-lock.json, package.json, src/components/Form/FieldTemplates/ObjectFieldTemplate.tsx, src/components/Form/Form.stories.tsx, src/components/Form/Widgets/PasswordWidget.tsx, src/components/Form/Widgets/SelectWidget.tsx, src/components/Form/index.tsx, src/index.ts, src/theme.ts
=> Add form component

src/components/Form/Widgets/SelectWidget.tsx
=> Fix Autocomplete widget selection

src/components/Form/index.tsx, src/index.ts, src/theme.ts
=> Export missing types and fix tooltip arrow

package-lock.json, package.json, src/components/Code/index.tsx, src/components/Markdown/Markdown.stories.tsx, src/components/Markdown/index.tsx, src/theme.ts
Custom colors in theme were mapped to the new color system, there are a few differences:
=> Replace absolute values for colors with design tokens

src/theme.ts
=> Fix primary color too light

package-lock.json, package.json, src/components/Form/Form.stories.tsx, src/components/Form/Widgets/FileWidget.tsx, src/components/Form/index.tsx, src/index.ts
=> Add FileWidget to RJSForm

src/components/Form/Widgets/FileWidget.tsx, src/index.ts
=> Expose FileWidget subtypings and matches RJSF errors styling

src/components/Form/Widgets/FileWidget.tsx
=> Fix click open dialog on some browsers

src/components/Form/index.tsx, src/theme.ts
=> Move Paper boxshadow style to the form theme

src/components/Form/Widgets/FileWidget.tsx
=> Add compatibility for multiple selection in the fileWidget

src/components/CookiesBanner/index.tsx
=> CookieBanner: Avoid calling onInit on every re-render

src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/index.tsx, src/index.ts
=> Add custom tooltip component

src/components/Form/FieldTemplates/ObjectFieldTemplate.tsx, src/components/Form/Widgets/SelectWidget.tsx, src/components/Form/index.tsx, src/index.ts, src/theme.ts
=> Add missing ref on RJSForm and missing Grid system on ObjectField uiSchema

src/index.ts
Export OrderedListItem
Connects-to: https://github.com/balena-io/balena-ui/pull/6371
=> Export OrderedListItem

src/components/Form/Widgets/PasswordWidget.tsx
Related-to: https://github.com/balena-io/balena-ui/pull/6365
=> RJSForm PasswordWidget: Lazy-load zxcvbn dependency

src/components/Form/index.tsx, src/index.ts, src/utils/index.ts
=> Add getBoundingContainerRect util

src/components/ButtonWithTracking/index.tsx, src/components/DropDownButton/index.tsx, src/components/Tooltip/index.tsx
=> Refactor Dropdown component to add menu support

src/components/DropDownButton/DropDownButton.stories.tsx, src/components/DropDownButton/index.tsx
=> Fix DropDown arrow

src/components/IconButtonWithTracking/IconButtonWithTacking.stories.tsx, src/components/IconButtonWithTracking/index.tsx
=> Add IconButtonWithTracking component

src/index.ts
=> Add missing IconButtonWithTracking export

src/components/DropDownButton/index.tsx
=> Fix DropDownMenu component

package-lock.json, package.json, src/components/Form/PasswordStrength.tsx, src/components/Form/Widgets/PasswordWidget.tsx
=> Add dynamic import on zxcvbn

tsconfig.json
=> Drop support for non-es2017 compliant browsers

src/components/Img/index.tsx
Img: Fix image not updating when `src` prop updates
=> Img: Fix image not updating when `src` prop updates

src/docs/20_foundations/20_colors.mdx, src/docs/utils.tsx
=> Show hex value on colors page

src/components/ButtonWithTracking/index.tsx, src/components/DropDownButton/index.tsx, src/components/IconButtonWithTracking/index.tsx
=> Adapt tooltip typing

package-lock.json, package.json, src/components/Spinner/Spinner.stories.tsx, src/components/Spinner/index.tsx, src/index.tsx, src/theme.tsx
Add Spinner component
Connects-to: https://github.com/balena-io/balena-ui/pull/6516
Connects-to: https://github.com/balena-io-modules/autoui/pull/79
=> Add Spinner component

src/index.tsx
Export UIMarker and MapProps types
=> Export UIMarker and MapProps types

src/theme.tsx
=> Add LinearProgress styling

src/components/DownloadImageDialog/ImageForm.tsx
=> DownloadImage: Add an e2e ID on the "show outdated versions" checkbox

src/components/VirtualizedAutocomplete/index.tsx
not using the useEffect as we need to do some structural changes. I would try to make the component more organised
=> Reduce VirtualizedAutocomplete change requests

package-lock.json, package.json, src/docs/30_mui_components/datagrid.mdx, src/docs/30_mui_components/table.mdx, src/index.tsx, src/theme.tsx
Add Table styling
Connects-to: https://github.com/balena-io/balena-ui/pull/6521
=> Add Table styling

src/components/Spinner/index.tsx
=> Spinner: Fix `sx` prop

.storybook/main.ts, .storybook/preview.tsx, package-lock.json, package.json, src/components/Chip/Chip.stories.tsx, src/components/Chip/index.tsx, src/components/DownloadImageDialog/ImageForm.tsx, src/components/DownloadImageDialog/OsTypeSelector.tsx, src/docs/20_foundations/20_colors.mdx, src/docs/30_mui_components/chip.mdx, src/index.tsx, src/theme.tsx
Add styling for the Chip component.
Export the Chip component from MUI but with fewer props.
=> Add chip styling

.storybook/docs.css, .storybook/global.css, .storybook/manager.ts, package-lock.json, package.json, src/components/Code/index.tsx, src/components/Copy/Copy.stories.tsx, src/components/Copy/index.tsx, src/components/DialogWithCloseButton/index.tsx, src/components/DownloadImageDialog/VariantSelector.tsx, src/components/Form/index.tsx, src/components/LimitedRowImages/index.tsx, src/components/Spinner/index.tsx, src/docs/20_foundations/30_typography.mdx, src/docs/utils.tsx, src/index.tsx, src/theme.tsx
=> Adapt typography styling

src/docs/30_mui_components/textfield.mdx, src/theme.tsx
=> Fix textfield bottom border on standard variant

src/components/Form/Widgets/SelectWidget.tsx
=> Form/SelectWidget: Use deep equality checking for value and options

package-lock.json, package.json, src/components/Chip/index.tsx, src/components/Copy/index.tsx, src/components/Form/Widgets/FileWidget.tsx, src/components/Spinner/index.tsx, src/docs/30_mui_components/chip.mdx, src/index.tsx, src/theme.tsx
=> Export FileWidget as component rather than type

src/components/CollectionSummary/CollectionSummary.stories.tsx, src/components/CollectionSummary/index.tsx, src/index.tsx
=> Add collection summary component

src/components/Form/Widgets/FileWidget.tsx
Fix FileWidget showing half-loading progress bar for all files
=> Fix FileWidget showing half-loading progress bar for all files

src/theme.tsx
=> Lighten background for light/secondary button

package-lock.json, package.json
=> Update TypeScript to 5.5.2

src/components/Form/Form.stories.tsx, src/components/Form/Widgets/SelectWidget.tsx
RJSF SelectWidget: Set `filterSelectedOptions` true if `multiple` true
=> RJSF SelectWidget: Set `filterSelectedOptions` true if `multiple` true

src/components/SettingsCard/SettingsCard.stories.tsx, src/components/SettingsCard/index.tsx, src/index.tsx
=> Add SettingsCard component

src/components/Form/Widgets/SelectWidget.tsx
RJSForm SelectWidget: Add `includeNoneOption` for adding a `None` option
=> RJSForm SelectWidget: Add `includeNoneOption` for adding a `None` option

package-lock.json, package.json, src/components/DownloadImageDialog/index.tsx, src/docs/30_mui_components/Alert.stories.tsx, src/theme.tsx
Breaking change: default `severity` for Alert changed from `success` to `neutral`
=> Add callout variant and improve Alerts

src/docs/30_mui_components/buttons.mdx, src/docs/utils.tsx, src/theme.tsx
=> Restyle ToggleButtonGroup component

src/components/Truncate/index.tsx
=> Fix truncate passing typography props

src/components/Form/Widgets/FileWidget.tsx
=> Fix FileUpload widget when multiple

src/docs/20_foundations/10_tokens.mdx, src/docs/30_mui_components/buttons.mdx, src/docs/utils.tsx, src/theme.tsx
* Add small improvements (color, sizes,...) to toggle buttons
* Remove most color variants for toggle buttons
* Make button height more consistent (37px)
* Fix design token list in the documentation
* Improve documentation for toggle buttons
=> Improve Toggle Buttons

src/theme.tsx
Link: Set the default cursor style to `pointer`
=> Link: Set the default cursor style to `pointer`

src/components/SnackbarProvider/index.tsx
Add `data-test` attribute to `Toast`s
=> Add `data-test` attribute to `Toast`s

src/components/Map/index.tsx
=> Fix Map existence checks for latitude and longitude

src/index.tsx
Export `analytics-client`
Connects-to: https://github.com/balena-io/balena-ui/pull/6688
=> Export `analytics-client`

src/components/VirtualizedAutocomplete/VirtualizedAutocomplete.stories.tsx, src/components/VirtualizedAutocomplete/index.tsx, src/theme.tsx
Autocomplete: Add border between items
=> Autocomplete: Add border between items

src/components/DownloadImageDialog/ImageForm.tsx
Download Image Dialog: Make `Show outdated versions` label clickable
=> Download Image Dialog: Make `Show outdated versions` label clickable

src/components/DownloadImageDialog/ImageForm.tsx
DownloadImageDialog: Fix versions dropdown not displaying selection
=> DownloadImageDialog: Fix versions dropdown not displaying selection

.github/renovate.json
Add `renovate.json` to `.github`
=> Add `renovate.json` to `.github`

src/components/HighlightedName/index.tsx, src/index.tsx
=> export the generateHexColorFromString helper

src/components/DownloadImageDialog/ImageForm.tsx, src/components/DownloadImageDialog/index.tsx
DownloadImageDialog: Fix extra `onFieldChange` calls
=> DownloadImageDialog: Fix extra `onFieldChange` calls

src/docs/30_mui_components/textfield.mdx, src/theme.tsx
=> Fix textarea vertical spacing being too big

src/components/Form/index.tsx
=> Form: Improve forwardRef typings

src/components/Announcement/index.tsx, src/theme.tsx
* Close the announcement when user has clicked on a link
* Announcement slides down when closed
* Better responsive styles
* Make room for the 'need help' button
=> Improvements to the announcement notification

src/components/Announcement/Announcement.stories.tsx, src/components/Announcement/index.tsx
will be added as part of the content in the UI
=> Remove mandatory link in the announcement component

src/components/Form/Widgets/FileWidget.tsx, src/hooks/useRandomUUID.ts, src/index.tsx
=> Add useRandomUUID hook

package-lock.json, package.json, src/docs/30_mui_components/buttons.mdx, src/docs/30_mui_components/pagination.mdx, src/docs/30_mui_components/table.mdx, src/theme.tsx
=> Restyle components

src/components/Tabs/index.tsx
=> Tabs: Add `leftElement` prop

src/hooks/useTranslations.ts
=> Fix missing `info.not_defined` translation

src/components/RJST/Lenses/types/table.tsx
=> Add an event on page view for table column settings

src/components/RJST/components/Filters/FocusSearch.tsx, src/components/RJST/models/helpers.ts, src/components/RJST/schemaOps.ts, src/index.tsx
=> Improve typings and export missing PineFilterOption interface

src/components/RJST/Filters/PersistentFilters.tsx
=> RJST Filters: Fix trimming leading `0`s from int-like strings

src/components/RJST/Actions/Update.tsx, src/components/RJST/components/Filters/Summary.tsx
=> Add `data-test`s to some RJST components

src/components/DownloadImageDialog/index.tsx, src/components/DownloadImageDialog/utils.ts
=> Improve error handling for inaccessible download URLs by providing a fallback action

package-lock.json, package.json
=> Update TypeScript to 5.8.2

src/components/DownloadImageDialog/ImageForm.tsx
=> DownloadImageDialog: Refactor the handleVersionChange

src/theme.tsx
=> Remove unnecessary `MuiMenuItem` styling

src/components/Form/Widgets/FileWidget.tsx
=> Fix upload file widget not working on some browsers

src/components/DownloadImageDialog/ImageForm.tsx, src/components/Form/Widgets/SelectWidget.tsx, src/components/TagManagementDialog/AddTagForm.tsx
See: https://github.com/facebook/react/issues/2882#issuecomment-70931554
=> Fix input autocomplete error

src/components/RJST/components/Table/TableHeader.tsx
=> RJST: Fix nested `th` and `thead` console warning

src/components/RJST/components/Widget/Formats/TxtWidget.tsx, src/components/RJST/components/Widget/index.tsx
=> Widgets: Fix `extraFormats` and `extraContexts` console errors

src/components/VirtualizedAutocomplete/index.tsx
=> Momentary virtualized autocomplete loadNext fix

package-lock.json, package.json
=> Update analytics-client to 2.1.0

src/components/DownloadImageDialog/ImageForm.tsx, src/components/DownloadImageDialog/OsTypeSelector.tsx, src/components/DownloadImageDialog/VariantSelector.tsx, src/components/DownloadImageDialog/index.tsx, src/theme.tsx
=> DownloadImageDialog: Move development variant warning to a callout

src/components/RJST/components/Table/TableCell.tsx
=> RJST: Make primary columns bold by default

src/components/RJST/components/Table/TableActions.tsx
=> Experiment: Allow column reordering with `reducedDefaultDeviceColumnsAndReordering` feature flag

src/components/Form/Widgets/SelectWidget.tsx
See: https://balena.fibery.io/Work/Project/re-pitching-API-Limit-size-of-large-fields-975
=> Form/SelectWidget: Support the placeholder property

src/components/DownloadImageDialog/ApplicationInstructions.tsx, src/components/DownloadImageDialog/models.ts, src/components/RJST/RJST.stories.tsx, src/components/RJST/components/Widget/Formats/BooleanAsIconWidget.tsx, src/components/RJST/components/Widget/Formats/CodeWidget.tsx, src/components/RJST/components/Widget/Formats/DisabledTextWidget.tsx, src/components/RJST/components/Widget/Formats/DurationWidget.tsx, src/components/RJST/components/Widget/Formats/ElapsedTimeWidget.tsx, src/components/RJST/components/Widget/Formats/HashWidget.tsx, src/components/RJST/components/Widget/Formats/PercentageWidget.tsx, src/components/RJST/components/Widget/Formats/PlaceholderTextWidget.tsx, src/components/RJST/components/Widget/Formats/TemperatureWidget.tsx, src/components/RJST/components/Widget/Formats/TxtWidget.tsx, src/components/RJST/components/Widget/Formats/WrapWidget.tsx, src/components/RJST/components/Widget/index.tsx, src/components/RJST/components/Widget/utils.ts, src/components/RJST/index.tsx, src/components/RJST/models/helpers.ts, src/index.tsx
Fibery: https://balena.fibery.io/Work/Project/Improve-WidgetFactory-clarity-1443
=> MAJOR: Improve Widget clarity + misc

src/components/Form/Widgets/FileWidget.tsx
Project: https://balena.fibery.io/Work/Project/Zendesk-upload-file-issue-1844
=> Fix FileWidget upload when `multiple`
