- src/components/DialogWithCloseButton/index.tsx
Fix DialogTitle fontSize being overriden by h6 fontSize
> Fix DialogTitle fontSize being overriden by h6 fontSize

- src/theme.ts
MUI Grid: Set the default value for `spacing` to be 2
Connects-to: https://github.com/balena-io/balena-ui/pull/6372
> MUI Grid: Set the default value for `spacing` to be 2

- src/components/MUILinkWithTracking/index.tsx
MUILinkWithTracking: Set `'_blank'` as the default value for `target`
> MUILinkWithTracking: Set `'_blank'` as the default value for `target`

- src/components/Img/index.tsx
Fix `Img` component's `onError` usage
> Fix `Img` component's `onError` usage

- src/index.ts
The library will be removed in https://github.com/balena-io-modules/ui-shared-components/pull/67, which will also replace internal iconMaterial use
> Remove icons-material export to improve bundle size

- package-lock.json
- package.json
- src/components/DialogWithCloseButton/index.tsx
- src/docs/30_mui_components/buttons.mdx
- src/theme.ts
Fix icon size too large (went from 14px to 20px after the buttons migration) and improve Icon Button styles.
> Improve icon styles

- src/theme.ts
Remove paddings around buttons with the variant `text`, disable the background color on hover and the ripple effect on active.
> Fix text button styling

- src/components/Form/Widgets/SelectWidget.tsx
RJSF SelectWidget: Fix form thinking field is empty when `multiple` and `required`
> RJSF SelectWidget: Fix form thinking field is empty when `multiple` and `required`

- src/components/DownloadImageDialog/ApplicationInstructions.tsx
- src/components/DownloadImageDialog/DownloadImageDialog.stories.tsx
- src/components/DownloadImageDialog/index.tsx
- src/components/DownloadImageDialog/models.ts
See: https://balena.fibery.io/Work/Project/Stop-using-device-type.json-fields-in-the-UI-791
> DownloadImageDialog: Drop support for device types with docker-image deployArtifact

- src/components/Tabs/index.tsx
Tabs: Use MUI's `scrollable` variant
> Tabs: Use MUI's `scrollable` variant

- src/components/Form/Widgets/FileWidget.tsx
- src/components/Map/index.tsx
- src/components/SimpleConfirmationDialog/SimpleConfirmationDialog.stories.tsx
- src/components/SimpleConfirmationDialog/index.tsx
- src/components/Tag/Tag.stories.tsx
- src/components/Tag/index.tsx
- src/components/TagManagementDialog/AddTagForm.tsx
- src/components/TagManagementDialog/TagLabel.tsx
- src/components/TagManagementDialog/TagManagementDialog.stories.tsx
- src/components/TagManagementDialog/index.tsx
- src/components/TagManagementDialog/models.ts
- src/components/TagManagementDialog/tag-management-service.ts
- src/components/TagManagementDialog/utils.ts
- src/components/VirtualizedAutocomplete/index.tsx
- src/contexts/TranslationContext.tsx
- src/hooks/useTranslations.ts
- src/index.tsx
> Add Tag, TagManagementDialog and SimpleConfirmationDialog components

- src/components/DownloadImageDialog/ImageForm.tsx
Resolves: https://github.com/balena-io/balena-ui/issues/6936
> DownloadImageDialog: Show name instead of slug in device type Autocomplete

- src/components/DownloadImageDialog/ImageForm.tsx
An extra case that we forgot and used the
stripped version instead of the raw version.
See: https://balena.zulipchat.com/#narrow/channel/403752-channel.2Fsupport-help/topic/Orange.20pi.20Zero.20image.20download.20does.20not.20work/near/502224287
> DownloadImageDialog: Fix downloading the auto-selected release when it has variants

- src/components/Code/index.tsx
See: https://mui.com/material-ui/guides/composition/#caveat-with-refs
> Fix `Tooltip` not working with `Code` due to not forwarding ref

- src/components/VirtualizedAutocomplete/index.tsx
> VirtualizedAutocomplete: Fix console error caused by passing `loadNext` to `Autocomplete`

- src/components/RJST/Lenses/types/index.ts
- src/components/RJST/Lenses/types/table.tsx
- src/components/RJST/components/Table/AddTagHandler.tsx
- src/components/RJST/components/Table/TableActions.tsx
- src/components/RJST/components/Table/TableCell.tsx
- src/components/RJST/components/Table/TableHeader.tsx
- src/components/RJST/components/Table/TableRow.tsx
- src/components/RJST/components/Table/TableToolbar.tsx
- src/components/RJST/components/Table/index.tsx
- src/components/RJST/components/Table/useColumns.ts
- src/components/RJST/components/Table/utils.ts
- src/components/RJST/index.tsx
- src/components/RJST/oData/jsonToOData.ts
- src/components/RJST/schemaOps.ts
Depends-on: https://github.com/balena-io-modules/odata-to-abstract-sql/pull/165
See: https://balena.fibery.io/Work/Project/Shape--Build-Add-support-for-sorting-on-user-selected-tag-columns-in-the-server-side-paginated-devic-912
> Add server-side ordering for tags

- package-lock.json
- package.json
Atm installing `^6.0.0-beta.22` results installing `6.0.0-dev.240424162023-9968b4889d` which is actually a lower version than `6.0.0-beta.22` .
Picked this version b/c it's already tested in some other projects.
See: https://www.npmjs.com/package/@mui/lab?activeTab=versions
See: [#channel/support-help > ui-shared-component ^6.0.0-beta.22 unexpected results @ 💬](https://balena.zulipchat.com/#narrow/channel/403752-channel.2Fsupport-help/topic/ui-shared-component.20.5E6.2E0.2E0-beta.2E22.20unexpected.20results/near/511464489)
> Pin @mui/lab to 6.0.0-beta.24 to avoid installing beta-dev versions

- src/components/RJST/Lenses/types/table.tsx
- src/components/RJST/components/Table/TableActions.tsx
- src/components/RJST/components/Table/TableToolbar.tsx
- src/components/RJST/components/Table/index.tsx
Fibery: https://balena.fibery.io/Work/Improvement/Track-clicks-on-the-Manage-columns-action-2746
> RJST Table: Add `onManageColumnsOpen` prop and track clicks

- src/components/DownloadImageDialog/ImageForm.tsx
- src/components/DownloadImageDialog/index.tsx
See: https://balena.fibery.io/Work/Project/DownloadImageDialog-Fix-the-variant-selection-for-non-unified-OS-releases-1405
> DownloadImageDialog: Fix the variant selection for non-unified OS releases

- src/components/RJST/RJST.stories.tsx
- src/components/RJST/index.tsx
- src/components/RJST/models/helpers.ts
- src/index.tsx
Fibery: https://balena.fibery.io/Work/Project/Change-Membership-Role-Permissions-to-not-have-inheritance-in-the-UI-1393
Connects-to: https://github.com/balena-io/balena-ui/pull/7126
> RJST helpers: Deprecate rjstGetModelForCollection in favor of `rjstGetModelForCollection2`
